/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from "react";

export function Model(props) {
    const { nodes } = props
    return (
        <group {...props} dispose={null}>
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Cube.geometry}
                material={nodes.Cube.material}
                position={[0, 0.07, -0.22]}
                rotation={[Math.PI / 2, Math.PI / 6, 0]}
            />

            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere001.geometry}
                material={nodes.Sphere001.material}
                position={[-0.3, 0.23, 0.43]}
                rotation={[Math.PI / 2, -1.18, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere002.geometry}
                material={nodes.Sphere002.material}
                position={[0.01, 0.39, 0.43]}
                rotation={[Math.PI / 2, 1.16, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere003.geometry}
                material={nodes.Sphere003.material}
                position={[0.16, 0.65, 0.43]}
                rotation={[Math.PI / 2, 1.07, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere004.geometry}
                material={nodes.Sphere004.material}
                position={[-0.46, 0.48, 0.43]}
                rotation={[Math.PI / 2, -1.21, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere005.geometry}
                material={nodes.Sphere005.material}
                position={[-0.64, 0.73, 0.43]}
                rotation={[Math.PI / 2, -1.16, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere006.geometry}
                material={nodes.Sphere006.material}
                position={[-0.79, 0.98, 0.43]}
                rotation={[Math.PI / 2, -1.2, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere007.geometry}
                material={nodes.Sphere007.material}
                position={[-0.93, 1.23, 0.43]}
                rotation={[Math.PI / 2, -1.31, Math.PI / 2]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere008.geometry}
                material={nodes.Sphere008.material}
                position={[-1.06, 1.5, 0.43]}
                rotation={[1.57, -1.42, 1.57]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere009.geometry}
                material={nodes.Sphere009.material}
                position={[-0.02, 0.1, 0.43]}
                rotation={[1.57, 1.57, 1.57]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere010.geometry}
                material={nodes.Sphere010.material}
                position={[-1.15, 1.88, 0.17]}
                rotation={[-1.41, -1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere011.geometry}
                material={nodes.Sphere011.material}
                position={[0.28, 0.88, 0.2]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere012.geometry}
                material={nodes.Sphere012.material}
                position={[0.28, 0.88, -0.13]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere013.geometry}
                material={nodes.Sphere013.material}
                position={[0.23, 0.61, -0.38]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere015.geometry}
                material={nodes.Sphere015.material}
                position={[-1.14, 1.89, -0.13]}
                rotation={[-1.75, -1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere016.geometry}
                material={nodes.Sphere016.material}
                position={[-1.08, 1.63, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere017.geometry}
                material={nodes.Sphere017.material}
                position={[-1.11, 1.34, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere032.geometry}
                material={nodes.Sphere032.material}
                position={[0.15, -0.7, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere033.geometry}
                material={nodes.Sphere033.material}
                position={[0.23, -0.42, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere034.geometry}
                material={nodes.Sphere034.material}
                position={[0.24, -0.12, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
            <mesh
                castShadow
                receiveShadow
                geometry={nodes.Sphere035.geometry}
                material={nodes.Sphere035.material}
                position={[0.24, 0.19, -0.39]}
                rotation={[-Math.PI, 1.57, 0]}
            />
        </group>
    );
}

